src/Entity/Availability.php
<?php

namespace App\Entity;

use App\Repository\AvailabilityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use DateTimeImmutable;

use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AvailabilityRepository::class)]
class Availability
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Assert\NotNull()]
    private ?DateTimeImmutable $start_date = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Assert\NotNull()]
    private ?DateTimeImmutable $end_date = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\PositiveOrZero()]
    private ?float $price = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'availabilities')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicle $vehicle = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeImmutable
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeImmutable $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeImmutable
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeImmutable $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getFormattedStartDate(): ?string
    {
        return $this->start_date ? $this->start_date->format('Y-m-d') : null;
    }

    public function getFormattedEndDate(): ?string
    {
        return $this->end_date ? $this->end_date->format('Y-m-d') : null;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): static
    {
        $this->vehicle = $vehicle;

        return $this;
    }
}

src/Form/AvailabilityType.php
<?php

namespace App\Form;

use App\Entity\Availability;
use App\Entity\Vehicle;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class AvailabilityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_date', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Date de début',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\NotNull()
                ]
            ])
            ->add('end_date', DateType::class, [
                'widget' => 'single_text',
                 'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Date de fin',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\NotNull()
                ]
           ])
            ->add('price', MoneyType::class, [
                 'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Prix',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Positive()
                ]
            ])
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'Disponible' => 'Disponible'
                ],
                 'attr' => [
                    'class' => 'btn btn-primary mt-4'
                ],
                'constraints' => [
                    new Assert\NotBlank()
                ]
            ])
            ->add('vehicle', EntityType::class, [
                'class' => Vehicle::class,
                'choice_label' => 'id',
                 'attr' => [
                    'class' => 'form-control'
                ],
                'label' => 'Véhicule',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
            ])
            ->add('submit', SubmitType::class, [
                'attr' =>[
                    'class' => 'btn btn-primary mt-4'
                ],
                'label' => 'Créer une disponibilité'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Availability::class,
        ]);
    }
}

src/Controller/AvailabilityController.php
<?php

namespace App\Controller;

use App\Entity\Availability;
use App\Form\AvailabilityType;
use App\Form\SearchAvailabilitiesType;
use App\Repository\AvailabilityRepository;
use App\Repository\VehicleRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Attribute\Route;

class AvailabilityController extends AbstractController
{

    #[Route('/disponibilite', name: 'availability.index', methods: ['GET'])]
    public function index(AvailabilityRepository $repository, PaginatorInterface $paginator, Request $request) : Response {
        $availabilities = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('pages/availability/index.html.twig', [
            'availabilities' => $availabilities
        ]);
    }

    #[Route('/disponibilite/recherche', name: 'availability.search', methods: ['GET', 'POST'])]
    public function search(AvailabilityRepository $availabilityRepository,
        Request $request,
        SessionInterface $session
        ) : Response {

        $form = $this->createForm(SearchAvailabilitiesType::class);
        $form->handleRequest(($request));

        if($form->isSubmitted()){
            $formStartDate = $form->get('start_date')->getData();
            $formEndDate = $form->get('end_date')->getData();

            $startDate = new DateTimeImmutable($formStartDate->format('Y-m-d'));
            $endDate = new DateTimeImmutable($formEndDate->format('Y-m-d'));
            
            $qb = $availabilityRepository->findByDateRange($startDate, $endDate);
            $availabilities = $qb->getQuery()->getResult();

            $priceMapping = [];

            foreach ($availabilities as $availability){
                $price = $availability->getPrice();
                $vehicleId = $availability->getVehicle()->getId();

                $priceMapping[$vehicleId] = $price;
            }
            $filteredVehicles = array_map(
                fn($availability) => $availability->getVehicle(),
                $availabilities
            );
            
            foreach ($filteredVehicles as $vehicle) {
                $vehicleId = $vehicle->getId();
                if (isset($priceMapping[$vehicleId])) {
                    $vehicle->setPrice($priceMapping[$vehicleId]);
                }
            }
            
            $session->set('search_data', [
                'filteredVehicles' => $filteredVehicles,
            ]);
            return $this->redirectToRoute('availability.results', [
            ]);
            }

        return $this->render('pages/availability/search.html.twig', [
           'form' => $form->createView(),
        ]);
    }

    #[Route('/disponibilite/resultat', name: 'availability.results', methods: ['GET'])]
    public function results(PaginatorInterface $paginator, SessionInterface $session, Request $request) : Response {
        $searchData = $session->get('search_data', []);
        $filteredVehicles = $searchData['filteredVehicles'] ?? [];

        $vehicles = $paginator->paginate(
            $filteredVehicles,
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('pages/availability/results.html.twig', [
         'filteredVehicles' => $filteredVehicles,
         'vehicles' => $vehicles
        ]);
    }

    #[Route('/disponibilite/nouveau', name: 'availability.new')]
    public function new(Request $request, EntityManagerInterface $manager): Response
    {
        $availability = new Availability();

        $form = $this->createForm(AvailabilityType::class, $availability);

        $form->handleRequest(($request));
        if($form->isSubmitted() && $form->isValid()){
            $availability = $form->getData();

            $manager->persist($availability);
            $manager->flush();
            
            $this->addFlash(
                'success',
                'Disponibilité créée !'
            );
            return $this->redirectToRoute('availability.index');
        }

        return $this->render('pages/availability/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/disponibilite/edition/{id}', 'availability.edit', methods: ['GET', 'POST'])]
    public function edit(Availability $availability, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(AvailabilityType::class, $availability);
        
            $form->handleRequest($request);
            if($form->isSubmitted() && $form->isValid()){
                $availability = $form->getData();
            
                $manager->persist($availability);
                $manager->flush();

                $this->addFlash(
                    'success',
                    'Votre disponibilité a été modifiée !'
                );

                return $this->redirectToRoute('availability.index');
            }
        return $this->render('pages/availability/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/disponibilite/suppression/{id}', 'availability.delete', methods: ['GET'])]
    public function delete(EntityManagerInterface $manager, Availability $availability) : Response 
    {
        $manager->remove($availability);
        $manager->flush();

        $this->addFlash(
            'success',
            'Votre disponibilité a été supprimé !'
        );
        return $this->redirectToRoute('availability.index');
    }
}

templates/pages/availability/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">

      <h1 class="mt-4">Modification d'une disponibilité</h1>

      {{ form_start(form) }}

        <div class="form-group">
          {{ form_label(form.start_date) }}
          {{ form_widget(form.start_date) }}
          <div class="form-error">
            {{ form_errors(form.start_date) }}
          </div>
        </div>

        <div class="form-group">
          {{ form_label(form.end_date) }}
          {{ form_widget(form.end_date) }}
          <div class="form-error">
            {{ form_errors(form.end_date) }}
        </div>

        <div class="form-group">
          {{ form_label(form.price) }}
          {{ form_widget(form.price) }}
          <div class="form-error">
            {{ form_errors(form.price) }}
          </div>
        </div>
    
        <div class="form-group">
          {{ form_widget(form.status) }}
          <div class="form-error">
            {{ form_errors(form.status) }}
          </div>
        </div>

        <div class="form-group">
          {{ form_label(form.vehicle) }}
          {{ form_widget(form.vehicle) }}
          <div class="form-error">
            {{ form_errors(form.vehicle) }}
          </div>

           
        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>
        
      {{ form_end(form) }}
      
    </div>
{% endblock %}

templates/pages/availability/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}test Wikicampers - Liste des disponibilités{% endblock %}
{% block body %}
    <div class="container mt-4">
        {% if not availabilities is same as ([]) %}
            <h1>Liste des disponibilités</h1>
            <a href="{{ path('availability.new' )}}" class="btn btn-primary">Ajouter une disponibilité</a>
                {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                        {{ message }}
                </div>
            {% endfor %}
                <div class="count mt-4">
                    <h4>Il y a {{ availabilities.getTotalItemCount }} disponibilités au total.</h4>
                </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Date de début</th>
                    <th scope="col">Date de fin</th>
                    <th scope="col">Prix</th>
                    <th scope="col">Modifier</th>
                    <th scope="col">Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                    {% for availability in availabilities %}
                        <tr class="table-primary mt-4">
                            <th scope="row">{{ availability.id }}</th>
                            <td>{{ availability.formattedStartDate }}</td>
                            <td>{{ availability.formattedEndDate }}</td>
                            <td>{{ availability.price }}</td>
                              <td>
                                <a href="{{ path('availability.edit', { id: availability.id })}}" class="btn btn-info">Modifier</a>
                            </td> 
                            <td>
                                <a href="{{ path('availability.delete', { id: availability.id })}}" class="btn btn-warning">Supprimer</a>
                            </td> 
                        {% endfor %}
                </tbody>
            </table>
            <div class="navigation d-flex justify-content-center">
                {{ knp_pagination_render(availabilities) }}
            </div>
        {% else %}
            <h4>Il y n'y a pas de disponibilités.</h4>
        {% endif %}        
    </div>
{% endblock %}

templates/pages/availability/new.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="container">
        <h1 class="mt-4">Création d'une disponibilité</h1>
        {{ form_start(form) }}
    <div class="form-group">
      {{ form_label(form.start_date) }}
      {{ form_widget(form.start_date) }}
      <div class="form-error">
        {{ form_errors(form.start_date) }}
      </div>
    </div>
    <div class="form-group">
      {{ form_label(form.end_date) }}
      {{ form_widget(form.end_date) }}
      <div class="form-error">
        {{ form_errors(form.end_date) }}
      </div>
    <div class="form-group">
      {{ form_label(form.price) }}
      {{ form_widget(form.price) }}
      <div class="form-error">
        {{ form_errors(form.price) }}
      </div>
    </div> 
    <div class="form-group">
      {{ form_widget(form.status) }}
      <div class="form-error">
        {{ form_errors(form.status) }}
      </div>
    </div>
    <div class="form-group">
      {{ form_label(form.vehicle) }}
      {{ form_widget(form.vehicle) }}
      <div class="form-error">
        {{ form_errors(form.vehicle) }}
      </div>
    </div>   
    <div class="form-group">
        {{ form_row(form.submit) }}
    </div>    
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/pages/availability/results.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="container mt-4">
        {% if not vehicles is same as ([]) %}
            <h1>Liste des véhicules</h1>
            <a class="btn btn-primary btn-sm" href="recherche" role="button">Retour à la recherche</a>
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                        {{ message }}
                </div>
            {% endfor %}
            <div class="count mt-4">

                <h4>Il y a {{ vehicles.getTotalItemCount }} véhicules au total.</h4>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Marque</th>
                    <th scope="col">Modèle</th>
                    <th scope="col">Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for vehicle in vehicles %}
                        <tr class="table-primary mt-4">
                            <th scope="row">{{ vehicle.id }}</th>
                            <td>{{ vehicle.brand }}</td>
                            <td>{{ vehicle.model }}</td>
                            <td>{{ vehicle.price }}</td>
                    {% endfor %}
                </tbody>
            </table>
            <div class="navigation d-flex justify-content-center">
                {{ knp_pagination_render(vehicles) }}
            </div>
        {% else %}
            <h4>Il y n'y a pas véhicule.</h4>
        {% endif %}
    </div>
{% endblock %}

templates/pages/availability/search.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="container">
        <h1 class="mt-4">Recherche d'une disponibilité</h1>
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.start_date) }}
            {{ form_widget(form.start_date) }}
            <div class="form-error">
                {{ form_errors(form.start_date) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.end_date) }}
            {{ form_widget(form.end_date) }}
            <div class="form-error">
                {{ form_errors(form.end_date) }}
            </div>
        </div>          
        <div class="form-group">
            {{ form_row(form.submit) }}
        </div>    
        {{ form_end(form) }}
    </div>
{% endblock %}